apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: zenith-postgres
  namespace: database
spec:
  instances: 3
  storage:
    size: 2Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: app_db
      owner: app_user
      secret:
        name: postgres-db-secret

  managed:
    roles:
      - name: wikijs
        ensure: present
        login: true
        createdb: true
        passwordSecret:
          name: wikijs-db-secret
