apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-password-sync
  namespace: database
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    name: postgres-db-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: password
      remoteRef:
        key: postgres-credentials
        property: password
    - secretKey: username
      remoteRef:
        key: postgres-credentials
        property: username
