apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: database
spec:
  provider:
    vault:
      server: "http://192.168.252.74:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes-workload"
          role: "database-role"
          serviceAccountRef:
            name: "vault-auth-sa"