apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-database
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/letDouglas/zenith.git
    targetRevision: dev
    path: platform/workload/manifests/database
  destination:
    name: zenith-workload
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true