apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wikijs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/letDouglas/zenith.git
    targetRevision: main
    path: platform/workload/manifests/wikijs
    directory:
      exclude: 'ingress-service.yaml'
  destination:
    name: zenith-workload
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true