apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: zenith-ip-pool
  namespace: kube-system
spec:
  cidrs:
    - cidr: "192.168.64.240/29"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: zenith-l2-policy
  namespace: kube-system
spec:
  interfaces:
    - "^en.*"
    - "^eth.*"
  externalIPs: true
  loadBalancerIPs: true